# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1244e7f91c86dff3bf4d8e9c0389cf9c69a8ff8df830c404580d89281a243ce27c4bf24c88010ba57646f5df4f154da80dab06f4b856c204bec25784e84f89a6

test:
  secret_key_base: 07a398e8fa6d2a13693b18b032e19cfce50b68607eaef3bc112be6b219a01c2414cae6f049412e7b7d8f21a7467300b8cde04b1f62e46007b65f1f35bdebad47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
